using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace GenerateUserTypesFromPdb.UserTypes
{
    class GlobalsUserType : UserType
    {
        private Module module;

        public GlobalsUserType(Module module, string moduleName)
            : base(module.GlobalScope, new XmlType() { Name = "Globals" }, moduleName)
        {
            this.module = module;
        }

        public override string ClassName
        {
            get
            {
                return "ModuleGlobals";
            }
        }

        internal override IEnumerable<UserTypeField> ExtractFields(UserTypeFactory factory, UserTypeGenerationFlags options)
        {
            var fields = Symbol.Fields.OrderBy(s => s.Name).ToArray();
            bool useThisClass = options.HasFlag(UserTypeGenerationFlags.UseClassFieldsFromDiaSymbolProvider);
            string previousName = "";

            foreach (var field in fields)
            {
                if (string.IsNullOrEmpty(field.Type.Name))
                {
                    continue;
                }

                if (IsFieldFiltered(field) || field.Name == previousName)
                    continue;

                UserType userType;
                factory.TryGetUserType(field.Type.Name, out userType);

                if (userType == null)
                {
                    continue;
                }

                var userField = ExtractField(field, factory, options, forceIsStatic: true);

                userField.FieldName = userField.FieldName.Replace("?", "_").Replace("$", "_").Replace("@", "_").Replace(":", "_").Replace(" ", "_").Replace("<", "_").Replace(">", "_").Replace("*", "_").Replace(",", "_");
                userField.PropertyName = userField.PropertyName.Replace("?", "_").Replace("$", "_").Replace("@", "_").Replace(":", "_").Replace(" ", "_").Replace("<", "_").Replace(">", "_").Replace("*", "_").Replace(",", "_");

                yield return userField;
                previousName = field.Name;
            }

            foreach (var field in GetAutoGeneratedFields(false, useThisClass))
                yield return field;
        }


        protected override UserTypeTree GetBaseTypeString(TextWriter error, Symbol type, UserTypeFactory factory)
        {
            return new UserTypeStaticClass();
        }

        protected override IEnumerable<UserTypeConstructor> GenerateConstructors()
        {
            yield return new UserTypeConstructor()
            {
                ContainsFieldDefinitions = true,
                Static = true,
            };
        }
    }
}