language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.2
script:
  - dotnet build Utility/ExceptionDumper/ExceptionDumper.csproj
  - dotnet build Source/CsDebugScript.DbgEng/CsDebugScript.DbgEng.csproj
  - dotnet build Tests/CsDebugScript.Engine.Test/CsDebugScript.Engine.Test.csproj
  - dotnet build
