using System;

namespace DbgEng
{
    /// <summary>
    /// The following events are generated by the target.
    /// </summary>
    [Flags]
    public enum DebugEvent : uint
    {
        /// <summary>
        /// A breakpoint exception occurred in the target. Calls: <see cref="IDebugEventCallbacks.Breakpoint(IDebugBreakpoint)"/>.
        /// <note>Maps to DEBUG_EVENT_BREAKPOINT.</note>
        /// </summary>
        Breakpoint = 1,

        /// <summary>
        /// An exception debugging event occurred in the target. Calls: <see cref="IDebugEventCallbacks.Exception(ref _EXCEPTION_RECORD64, uint)"/>.
        /// <note>Maps to DEBUG_EVENT_EXCEPTION.</note>
        /// </summary>
        Exception = 2,

        /// <summary>
        /// A create-thread debugging event occurred in the target. Calls: <see cref="IDebugEventCallbacks.CreateThread(ulong, ulong, ulong)"/>.
        /// <note>Maps to DEBUG_EVENT_CREATE_THREAD.</note>
        /// </summary>
        CreateThread = 4,

        /// <summary>
        /// An exit-thread debugging event occurred in the target. Calls: <see cref="IDebugEventCallbacks.ExitThread(uint)"/>.
        /// <note>Maps to DEBUG_EVENT_EXIT_THREAD.</note>
        /// </summary>
        ExitThread = 8,

        /// <summary>
        /// A create-process debugging event occurred in the target. Calls: <see cref="IDebugEventCallbacks.CreateProcess(ulong, ulong, ulong, uint, string, string, uint, uint, ulong, ulong, ulong)"/>.
        /// <note>Maps to DEBUG_EVENT_CREATE_PROCESS.</note>
        /// </summary>
        CreateProcess = 16,

        /// <summary>
        /// An exit-process debugging event occurred in the target. Calls: <see cref="IDebugEventCallbacks.ExitProcess(uint)"/>.
        /// <note>Maps to DEBUG_EVENT_EXIT_PROCESS.</note>
        /// </summary>
        ExitProcess = 32,

        /// <summary>
        /// A module-load debugging event occurred in the target. Calls: <see cref="IDebugEventCallbacks.LoadModule(ulong, ulong, uint, string, string, uint, uint)"/>.
        /// <note>Maps to DEBUG_EVENT_LOAD_MODULE.</note>
        /// </summary>
        LoadModule = 64,

        /// <summary>
        /// A module-unload debugging event occurred in the target. Calls: <see cref="IDebugEventCallbacks.UnloadModule(string, ulong)"/>.
        /// <note>Maps to DEBUG_EVENT_UNLOAD_MODULE.</note>
        /// </summary>
        UnloadModule = 128,

        /// <summary>
        /// A system error occurred in the target. Calls: <see cref="IDebugEventCallbacks.SystemError(uint, uint)"/>.
        /// <note>Maps to DEBUG_EVENT_SYSTEM_ERROR.</note>
        /// </summary>
        SystemError = 256,

        /// <summary>
        /// A change has occurred in the session status. Calls: <see cref="IDebugEventCallbacks.SessionStatus(uint)"/>.
        /// <note>Maps to DEBUG_EVENT_SESSION_STATUS.</note>
        /// </summary>
        SessionStatus = 512,

        /// <summary>
        /// The engine has made or detected a change in the target status. Calls: <see cref="IDebugEventCallbacks.ChangeDebuggeeState(uint, ulong)"/>.
        /// <note>Maps to DEBUG_EVENT_CHANGE_DEBUGGEE_STATE.</note>
        /// </summary>
        ChangeDebuggeeState = 1024,

        /// <summary>
        /// The engine state has changed. Calls: <see cref="IDebugEventCallbacks.ChangeEngineState(uint, ulong)"/>.
        /// <note>Maps to DEBUG_EVENT_CHANGE_ENGINE_STATE.</note>
        /// </summary>
        ChangeEngineState = 2048,

        /// <summary>
        /// The symbol state has changed. Calls: <see cref="IDebugEventCallbacks.ChangeSymbolState(uint, ulong)"/>.
        /// <note>Maps to DEBUG_EVENT_CHANGE_SYMBOL_STATE.</note>
        /// </summary>
        ChangeSymbolState = 4096,
    }
}
