using System;

namespace DbgEng
{
    // TODO: This needs to dissapear in favor to defined enums...
    public enum Defines
    {
        DebugGetTextCompletionsNoDotCommands = 1,
        DebugGetTextCompletionsNoExtensionCommands,
        DebugGetTextCompletionsNoSymbols = 4,
        DebugGetTextCompletionsIsDotCommand = 1,
        DebugGetTextCompletionsIsExtensionCommand,
        DebugGetTextCompletionsIsSymbol = 4,
        DebugSrcfileSymbolToken = 0,
        DebugSrcfileSymbolTokenSourceCommandWide,
        DebugSrcfileSymbolChecksuminfo,
        DebugSyminfoBreakpointSourceLine = 0,
        DebugSyminfoImagehlpModulew64,
        DebugSyminfoGetSymbolNameByOffsetAndTagWide,
        DebugSyminfoGetModuleSymbolNamesAndOffsets,
        DebugSysobjinfoThreadBasicInformation = 0,
        DebugSysobjinfoThreadNameWide,
        DebugSysobjinfoCurrentProcessCookie,
        DebugTbinfoExitStatus = 1,
        DebugTbinfoPriorityClass,
        DebugTbinfoPriority = 4,
        DebugTbinfoTimes = 8,
        DebugTbinfoStartOffset = 16,
        DebugTbinfoAffinity = 32,
        DebugTbinfoAll = 63,
        DebugBreakpointCode = 0,
        DebugBreakpointData,
        DebugBreakpointTime,
        DebugBreakpointInline,
        DebugBreakpointGoOnly = 1,
        DebugBreakpointDeferred,
        DebugBreakpointEnabled = 4,
        DebugBreakpointAdderOnly = 8,
        DebugBreakpointOneShot = 16,
        DebugBreakRead = 1,
        DebugBreakWrite,
        DebugBreakExecute = 4,
        DebugBreakIo = 8,
        DebugIoutputKdProtocol = -2147483648,
        DebugIoutputRemoting = 1073741824,
        DebugIoutputBreakpoint = 536870912,
        DebugIoutputEvent = 268435456,
        DebugIoutputAddrTranslate = 134217728,
        DebugOutputIdentityDefault = 0,
        DebugClientUnknown = 0,
        DebugClientVsint,
        DebugClientNtsd,
        DebugClientNtkd,
        DebugClientCdb,
        DebugClientKd,
        DebugClientWindbg,
        DebugClientWinide,
        DebugStatusNoChange = 0,
        DebugStatusGo,
        DebugStatusGoHandled,
        DebugStatusGoNotHandled,
        DebugStatusStepOver,
        DebugStatusStepInto,
        DebugStatusBreak,
        DebugStatusNoDebuggee,
        DebugStatusStepBranch,
        DebugStatusIgnoreEvent,
        DebugStatusRestartRequested,
        DebugStatusReverseGo,
        DebugStatusReverseStepBranch,
        DebugStatusReverseStepOver,
        DebugStatusReverseStepInto,
        DebugStatusOutOfSync,
        DebugStatusWaitInput,
        DebugStatusTimeout,
        DebugStatusMask = 31,
        DebugInterruptActive = 0,
        DebugInterruptPassive,
        DebugInterruptExit,
        DebugCurrentDefault = 15,
        DebugCurrentSymbol = 1,
        DebugCurrentDisasm,
        DebugCurrentRegisters = 4,
        DebugCurrentSourceLine = 8,
        DebugDisasmEffectiveAddress = 1,
        DebugDisasmMatchingSymbols,
        DebugDisasmSourceLineNumber = 4,
        DebugDisasmSourceFileName = 8,
        DebugLevelSource = 0,
        DebugLevelAssembly,
        DebugEngoptIgnoreDbghelpVersion = 1,
        DebugEngoptIgnoreExtensionVersions,
        DebugEngoptAllowNetworkPaths = 4,
        DebugEngoptDisallowNetworkPaths = 8,
        DebugEngoptIgnoreLoaderExceptions = 16,
        DebugEngoptInitialBreak = 32,
        DebugEngoptInitialModuleBreak = 64,
        DebugEngoptFinalBreak = 128,
        DebugEngoptNoExecuteRepeat = 256,
        DebugEngoptFailIncompleteInformation = 512,
        DebugEngoptAllowReadOnlyBreakpoints = 1024,
        DebugEngoptSynchronizeBreakpoints = 2048,
        DebugEngoptDisallowShellCommands = 4096,
        DebugEngoptKdQuietMode = 8192,
        DebugEngoptDisableManagedSupport = 16384,
        DebugEngoptDisableModuleSymbolLoad = 32768,
        DebugEngoptDisableExecutionCommands = 65536,
        DebugEngoptDisallowImageFileMapping = 131072,
        DebugEngoptPreferDml = 262144,
        DebugEngoptDisablesqm = 524288,
        DebugEngoptDisableSteplinesOptions = 2097152,
        DebugEngoptAll = 3145727,
        DebugAnyId = -1,
        StackFrameTypeInit,
        StackFrameTypeStack,
        StackFrameTypeInline,
        StackFrameTypeIgnore = 255,
        DebugStackArguments = 1,
        DebugStackFunctionInfo,
        DebugStackSourceLine = 4,
        DebugStackFrameAddresses = 8,
        DebugStackColumnNames = 16,
        DebugStackNonvolatileRegisters = 32,
        DebugStackFrameNumbers = 64,
        DebugStackParameters = 128,
        DebugStackFrameAddressesRaOnly = 256,
        DebugStackFrameMemoryUsage = 512,
        DebugStackParametersNewline = 1024,
        DebugStackDml = 2048,
        DebugStackFrameOffsets = 4096,
        DebugStackProvider = 8192,
        DebugKernelConnection = 0,
        DebugKernelLocal,
        DebugKernelExdiDriver,
        DebugKernelIdna,
        DebugKernelInstallDriver,
        DebugUserWindowsProcess = 0,
        DebugUserWindowsProcessServer,
        DebugUserWindowsIdna,
        DebugExtensionAtEngine = 0,
        DebugFilterCreateThread = 0,
        DebugFilterExitThread,
        DebugFilterCreateProcess,
        DebugFilterExitProcess,
        DebugFilterLoadModule,
        DebugFilterUnloadModule,
        DebugFilterSystemError,
        DebugFilterInitialBreakpoint,
        DebugFilterInitialModuleLoad,
        DebugFilterDebuggeeOutput,
        DebugFilterBreak = 0,
        DebugFilterSecondChanceBreak,
        DebugFilterOutput,
        DebugFilterIgnore,
        DebugFilterRemove,
        DebugFilterGoHandled = 0,
        DebugFilterGoNotHandled,
        DebugWaitDefault = 0,
        DebugValueInvalid = 0,
        DebugValueInt8,
        DebugValueInt16,
        DebugValueInt32,
        DebugValueInt64,
        DebugValueFloat32,
        DebugValueFloat64,
        DebugValueFloat80,
        DebugValueFloat82,
        DebugValueFloat128,
        DebugValueVector64,
        DebugValueVector128,
        DebugValueTypes,
        DebugOutTextReplDefault = 0,
        DebugAsmoptDefault = 0,
        DebugAsmoptVerbose,
        DebugAsmoptNoCodeBytes,
        DebugAsmoptIgnoreOutputWidth = 4,
        DebugAsmoptSourceLineNumber = 8,
        DebugExprMasm = 0,
        DebugExprCplusplus,
        DebugEindexName = 0,
        DebugEindexFromStart = 0,
        DebugEindexFromEnd,
        DebugEindexFromCurrent,
        DebugLogDefault = 0,
        DebugLogAppend,
        DebugLogUnicode,
        DebugLogDml = 4,
        DebugSysverstrServicePack = 0,
        DebugSysverstrBuild,
        DebugManagedDisabled = 0,
        DebugManagedAllowed,
        DebugManagedDllLoaded,
        DebugManstrNone = 0,
        DebugManstrLoadedSupportDll,
        DebugManstrLoadStatus,
        DebugManresetDefault = 0,
        DebugManresetLoadDll,
        DebugExecFlagsNonblock = 1,
        DebugDataSpaceVirtual = 0,
        DebugDataSpacePhysical,
        DebugDataSpaceControl,
        DebugDataSpaceIo,
        DebugDataSpaceMsr,
        DebugDataSpaceBusData,
        DebugDataSpaceDebuggerData,
        DebugDataSpaceCount,
        DebugDataKernbase = 24,
        DebugDataBreakpointwithstatusaddr = 32,
        DebugDataSavedcontextaddr = 40,
        DebugDataKicallusermodeaddr = 56,
        DebugDataKeusercallbackdispatcheraddr = 64,
        DebugDataPsloadedmodulelistaddr = 72,
        DebugDataPsactiveprocessheadaddr = 80,
        DebugDataPspcidtableaddr = 88,
        DebugDataExpsystemresourceslistaddr = 96,
        DebugDataExppagedpooldescriptoraddr = 104,
        DebugDataExpnumberofpagedpoolsaddr = 112,
        DebugDataKetimeincrementaddr = 120,
        DebugDataKebugcheckcallbacklistheadaddr = 128,
        DebugDataKibugcheckdataaddr = 136,
        DebugDataIoperrorloglistheadaddr = 144,
        DebugDataObprootdirectoryobjectaddr = 152,
        DebugDataObptypeobjecttypeaddr = 160,
        DebugDataMmsystemcachestartaddr = 168,
        DebugDataMmsystemcacheendaddr = 176,
        DebugDataMmsystemcachewsaddr = 184,
        DebugDataMmpfndatabaseaddr = 192,
        DebugDataMmsystemptesstartaddr = 200,
        DebugDataMmsystemptesendaddr = 208,
        DebugDataMmsubsectionbaseaddr = 216,
        DebugDataMmnumberofpagingfilesaddr = 224,
        DebugDataMmlowestphysicalpageaddr = 232,
        DebugDataMmhighestphysicalpageaddr = 240,
        DebugDataMmnumberofphysicalpagesaddr = 248,
        DebugDataMmmaximumnonpagedpoolinbytesaddr = 256,
        DebugDataMmnonpagedsystemstartaddr = 264,
        DebugDataMmnonpagedpoolstartaddr = 272,
        DebugDataMmnonpagedpoolendaddr = 280,
        DebugDataMmpagedpoolstartaddr = 288,
        DebugDataMmpagedpoolendaddr = 296,
        DebugDataMmpagedpoolinformationaddr = 304,
        DebugDataMmpagesize = 312,
        DebugDataMmsizeofpagedpoolinbytesaddr = 320,
        DebugDataMmtotalcommitlimitaddr = 328,
        DebugDataMmtotalcommittedpagesaddr = 336,
        DebugDataMmsharedcommitaddr = 344,
        DebugDataMmdrivercommitaddr = 352,
        DebugDataMmprocesscommitaddr = 360,
        DebugDataMmpagedpoolcommitaddr = 368,
        DebugDataMmextendedcommitaddr = 376,
        DebugDataMmzeroedpagelistheadaddr = 384,
        DebugDataMmfreepagelistheadaddr = 392,
        DebugDataMmstandbypagelistheadaddr = 400,
        DebugDataMmmodifiedpagelistheadaddr = 408,
        DebugDataMmmodifiednowritepagelistheadaddr = 416,
        DebugDataMmavailablepagesaddr = 424,
        DebugDataMmresidentavailablepagesaddr = 432,
        DebugDataPooltracktableaddr = 440,
        DebugDataNonpagedpooldescriptoraddr = 448,
        DebugDataMmhighestuseraddressaddr = 456,
        DebugDataMmsystemrangestartaddr = 464,
        DebugDataMmuserprobeaddressaddr = 472,
        DebugDataKdprintcircularbufferaddr = 480,
        DebugDataKdprintcircularbufferendaddr = 488,
        DebugDataKdprintwritepointeraddr = 496,
        DebugDataKdprintrollovercountaddr = 504,
        DebugDataMmloadeduserimagelistaddr = 512,
        DebugDataNtbuildlabaddr = 520,
        DebugDataKinormalsystemcall = 528,
        DebugDataKiprocessorblockaddr = 536,
        DebugDataMmunloadeddriversaddr = 544,
        DebugDataMmlastunloadeddriveraddr = 552,
        DebugDataMmtriageactiontakenaddr = 560,
        DebugDataMmspecialpooltagaddr = 568,
        DebugDataKernelverifieraddr = 576,
        DebugDataMmverifierdataaddr = 584,
        DebugDataMmallocatednonpagedpooladdr = 592,
        DebugDataMmpeakcommitmentaddr = 600,
        DebugDataMmtotalcommitlimitmaximumaddr = 608,
        DebugDataCmntcsdversionaddr = 616,
        DebugDataMmphysicalmemoryblockaddr = 624,
        DebugDataMmsessionbase = 632,
        DebugDataMmsessionsize = 640,
        DebugDataMmsystemparenttablepage = 648,
        DebugDataMmvirtualtranslationbase = 656,
        DebugDataOffsetkthreadnextprocessor = 664,
        DebugDataOffsetkthreadteb = 666,
        DebugDataOffsetkthreadkernelstack = 668,
        DebugDataOffsetkthreadinitialstack = 670,
        DebugDataOffsetkthreadapcprocess = 672,
        DebugDataOffsetkthreadstate = 674,
        DebugDataOffsetkthreadbstore = 676,
        DebugDataOffsetkthreadbstorelimit = 678,
        DebugDataSizeeprocess = 680,
        DebugDataOffseteprocesspeb = 682,
        DebugDataOffseteprocessparentcid = 684,
        DebugDataOffseteprocessdirectorytablebase = 686,
        DebugDataSizeprcb = 688,
        DebugDataOffsetprcbdpcroutine = 690,
        DebugDataOffsetprcbcurrentthread = 692,
        DebugDataOffsetprcbmhz = 694,
        DebugDataOffsetprcbcputype = 696,
        DebugDataOffsetprcbvendorstring = 698,
        DebugDataOffsetprcbprocessorstate = 700,
        DebugDataOffsetprcbnumber = 702,
        DebugDataSizeethread = 704,
        DebugDataKdprintcircularbufferptraddr = 712,
        DebugDataKdprintbuffersizeaddr = 720,
        DebugDataMmbadpagesdetected = 800,
        DebugDataEtwpdebuggerdata = 816,
        DebugDataPtebase = 864,
        DebugDataPaeenabled = 100000,
        DebugDataShareduserdata = 100008,
        DebugDataProducttype = 100016,
        DebugDataSuitemask = 100024,
        DebugDataDumpwriterstatus = 100032,
        DebugDataDumpformatversion = 100040,
        DebugDataDumpwriterversion = 100048,
        DebugDataDumppowerstate = 100056,
        DebugDataDumpmmstorage = 100064,
        DebugDataDumpattributes = 100072,
        DebugDataKpcrOffset = 0,
        DebugDataKprcbOffset,
        DebugDataKthreadOffset,
        DebugDataBaseTranslationVirtualOffset,
        DebugDataProcessorIdentification,
        DebugDataProcessorSpeed,
        DebugHandleDataTypeBasic = 0,
        DebugHandleDataTypeTypeName,
        DebugHandleDataTypeObjectName,
        DebugHandleDataTypeHandleCount,
        DebugHandleDataTypeTypeNameWide,
        DebugHandleDataTypeObjectNameWide,
        DebugHandleDataTypeMiniThread1,
        DebugHandleDataTypeMiniMutant1,
        DebugHandleDataTypeMiniMutant2,
        DebugHandleDataTypePerHandleOperations,
        DebugHandleDataTypeAllHandleOperations,
        DebugHandleDataTypeMiniProcess1,
        DebugHandleDataTypeMiniProcess2,
        DebugHandleDataTypeMiniEvent1,
        DebugHandleDataTypeMiniSection1,
        DebugHandleDataTypeMiniSemaphore1,
        DebugOffsinfoVirtualSource = 1,
        DebugVsourceInvalid = 0,
        DebugVsourceDebuggee,
        DebugVsourceMappedImage,
        DebugVsourceDumpWithoutMeminfo,
        DebugVsearchDefault = 0,
        DebugVsearchWritableOnly,
        DebugPhysicalDefault = 0,
        DebugPhysicalCached,
        DebugPhysicalUncached,
        DebugPhysicalWriteCombined,
        DebugSessionActive = 0,
        DebugSessionEndSessionActiveTerminate,
        DebugSessionEndSessionActiveDetach,
        DebugSessionEndSessionPassive,
        DebugSessionEnd,
        DebugSessionReboot,
        DebugSessionHibernate,
        DebugSessionFailure,
        DebugCdsAll = -1,
        DebugCdsRegisters = 1,
        DebugCdsData,
        DebugCdsRefresh = 4,
        DebugCdsRefreshEvaluate = 1,
        DebugCdsRefreshExecute,
        DebugCdsRefreshExecutecommandfile,
        DebugCdsRefreshAddbreakpoint,
        DebugCdsRefreshRemovebreakpoint,
        DebugCdsRefreshWritevirtual,
        DebugCdsRefreshWritevirtualuncached,
        DebugCdsRefreshWritephysical,
        DebugCdsRefreshWritephysical2,
        DebugCdsRefreshSetvalue,
        DebugCdsRefreshSetvalue2,
        DebugCdsRefreshSetscope,
        DebugCdsRefreshSetscopeframebyindex,
        DebugCdsRefreshSetscopefromjitdebuginfo,
        DebugCdsRefreshSetscopefromstoredevent,
        DebugCdsRefreshInlinestep,
        DebugCdsRefreshInlinestepPseudo,
        DebugCesAll = -1,
        DebugCesCurrentThread = 1,
        DebugCesEffectiveProcessor,
        DebugCesBreakpoints = 4,
        DebugCesCodeLevel = 8,
        DebugCesExecutionStatus = 16,
        DebugCesEngineOptions = 32,
        DebugCesLogFile = 64,
        DebugCesRadix = 128,
        DebugCesEventFilters = 256,
        DebugCesProcessOptions = 512,
        DebugCesExtensions = 1024,
        DebugCesSystems = 2048,
        DebugCesAssemblyOptions = 4096,
        DebugCesExpressionSyntax = 8192,
        DebugCesTextReplacements = 16384,
        DebugCssAll = -1,
        DebugCssLoads = 1,
        DebugCssUnloads,
        DebugCssScope = 4,
        DebugCssPaths = 8,
        DebugCssSymbolOptions = 16,
        DebugCssTypeOptions = 32,
        DebugCssCollapseChildren = 64,
        DebugOutcbiExplicitFlush = 1,
        DebugOutcbiText,
        DebugOutcbiDml = 4,
        DebugOutcbiAnyFormat = 6,
        DebugOutcbText = 0,
        DebugOutcbDml,
        DebugOutcbExplicitFlush,
        DebugOutcbfCombinedExplicitFlush = 1,
        DebugOutcbfDmlHasTags,
        DebugOutcbfDmlHasSpecialCharacters = 4,
        DebugRegistersDefault = 0,
        DebugRegistersInt32,
        DebugRegistersInt64,
        DebugRegistersFloat = 4,
        DebugRegistersAll = 7,
        DebugRegisterSubRegister = 1,
        DebugRegsrcDebuggee = 0,
        DebugRegsrcExplicit,
        DebugRegsrcFrame,
        DebugOutputSymbolsDefault = 0,
        DebugOutputSymbolsNoNames,
        DebugOutputSymbolsNoOffsets,
        DebugOutputSymbolsNoValues = 4,
        DebugOutputSymbolsNoTypes = 16,
        DebugSymbolExpansionLevelMask = 15,
        DebugSymbolExpanded,
        DebugSymbolReadOnly = 32,
        DebugSymbolIsArray = 64,
        DebugSymbolIsFloat = 128,
        DebugSymbolIsArgument = 256,
        DebugSymbolIsLocal = 512,
        DebugSymentIsCode = 1,
        DebugSymentIsData,
        DebugSymentIsParameter = 4,
        DebugSymentIsLocal = 8,
        DebugSymentIsManaged = 16,
        DebugSymentIsSynthetic = 32,
        DebugModuleLoaded = 0,
        DebugModuleUnloaded,
        DebugModuleUserMode,
        DebugModuleExeModule = 4,
        DebugModuleExplicit = 8,
        DebugModuleSecondary = 16,
        DebugModuleSynthetic = 32,
        DebugModuleSymBadChecksum = 65536,
        DebugSymtypeNone = 0,
        DebugSymtypeCoff,
        DebugSymtypeCodeview,
        DebugSymtypePdb,
        DebugSymtypeExport,
        DebugSymtypeDeferred,
        DebugSymtypeSym,
        DebugSymtypeDia,
        DebugOuttypeDefault = 0,
        DebugOuttypeNoIndent,
        DebugOuttypeNoOffset,
        DebugOuttypeVerbose = 4,
        DebugOuttypeCompactOutput = 8,
        DebugOuttypeAddressOfField = 65536,
        DebugOuttypeAddressAtEnd = 131072,
        DebugOuttypeBlockRecurse = 2097152,
        DebugFindSourceDefault = 0,
        DebugFindSourceFullPath,
        DebugFindSourceBestMatch,
        DebugFindSourceNoSrcsrv = 4,
        DebugFindSourceTokenLookup = 8,
        DebugFindSourceWithChecksum = 16,
        ModuleOrdersMask = -268435456,
        ModuleOrdersLoadtime = 268435456,
        ModuleOrdersModulename = 536870912,
        DebugTypeoptsUnicodeDisplay = 1,
        DebugTypeoptsLongstatusDisplay,
        DebugTypeoptsForceradixOutput = 4,
        DebugTypeoptsMatchMaxsize = 8,
        DebugGetmodDefault = 0,
        DebugGetmodNoLoadedModules,
        DebugGetmodNoUnloadedModules,
        DebugAddsynthmodDefault = 0,
        DebugAddsynthmodZerobase,
        DebugAddsynthsymDefault = 0,
        DebugOutsymDefault = 0,
        DebugOutsymForceOffset,
        DebugOutsymSourceLine,
        DebugOutsymAllowDisplacement = 4,
        DebugGetfnentDefault = 0,
        DebugGetfnentRawEntryOnly,
        DebugSourceIsStatement = 1,
        DebugGselDefault = 0,
        DebugGselNoSymbolLoads,
        DebugGselAllowLower,
        DebugGselAllowHigher = 4,
        DebugGselNearestOnly = 8,
        DebugGselInlineCallsite = 16,
        DebugFrameDefault = 0,
        DebugFrameIgnoreInline,
        DebugCommandExceptionId = -606073410,
        DebugCmdexInvalid = 0,
        DebugCmdexAddEventString,
        DebugCmdexResetEventStrings,
        DebugExtinitHasCommandHelp = 1,
        DebugNotifySessionActive = 0,
        DebugNotifySessionInactive,
        DebugNotifySessionAccessible,
        DebugNotifySessionInaccessible,
        DebugKnownStructGetNames = 1,
        DebugKnownStructGetSingleLineOutput,
        DebugKnownStructSuppressTypeName,
        DebugExtQvalueDefault = 0,
        DebugExtPvalueDefault = 0,
        DebugExtPvtypeIsValue = 0,
        DebugExtPvtypeIsPointer
    }
}
