namespace DIA
{
    /// <summary>
    /// Specifies the target processor.
    /// <note>The processor is identified in the enumeration element after the <c>CV_CFL_*</c> prefix.</note>
    /// </summary>
    public enum CV_CPU_TYPE_e : uint
    {
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
        CV_CFL_8080,
        CV_CFL_8086,
        CV_CFL_80286,
        CV_CFL_80386,
        CV_CFL_80486,
        CV_CFL_PENTIUM,
        CV_CFL_PENTIUMII,
        CV_CFL_PENTIUMPRO = 6,
        CV_CFL_PENTIUMIII,
        CV_CFL_MIPS = 16,
        CV_CFL_MIPSR4000 = 16,
        CV_CFL_MIPS16,
        CV_CFL_MIPS32,
        CV_CFL_MIPS64,
        CV_CFL_MIPSI,
        CV_CFL_MIPSII,
        CV_CFL_MIPSIII,
        CV_CFL_MIPSIV,
        CV_CFL_MIPSV,
        CV_CFL_M68000 = 32,
        CV_CFL_M68010,
        CV_CFL_M68020,
        CV_CFL_M68030,
        CV_CFL_M68040,
        CV_CFL_ALPHA = 48,
        CV_CFL_ALPHA_21064 = 48,
        CV_CFL_ALPHA_21164,
        CV_CFL_ALPHA_21164A,
        CV_CFL_ALPHA_21264,
        CV_CFL_ALPHA_21364,
        CV_CFL_PPC601 = 64,
        CV_CFL_PPC603,
        CV_CFL_PPC604,
        CV_CFL_PPC620,
        CV_CFL_PPCFP,
        CV_CFL_PPCBE,
        CV_CFL_SH3 = 80,
        CV_CFL_SH3E,
        CV_CFL_SH3DSP,
        CV_CFL_SH4,
        CV_CFL_SHMEDIA,
        CV_CFL_ARM3 = 96,
        CV_CFL_ARM4,
        CV_CFL_ARM4T,
        CV_CFL_ARM5,
        CV_CFL_ARM5T,
        CV_CFL_ARM6,
        CV_CFL_ARM_XMAC,
        CV_CFL_ARM_WMMX,
        CV_CFL_ARM7,
        CV_CFL_OMNI = 112,
        CV_CFL_IA64 = 128,
        CV_CFL_IA64_1 = 128,
        CV_CFL_IA64_2,
        CV_CFL_CEE = 144,
        CV_CFL_AM33 = 160,
        CV_CFL_M32R = 176,
        CV_CFL_TRICORE = 192,
        CV_CFL_X64 = 208,
        CV_CFL_AMD64 = 208,
        CV_CFL_EBC = 224,
        CV_CFL_THUMB = 240,
        CV_CFL_ARMNT = 244,
        CV_CFL_ARM64 = 246,
        CV_CFL_HYBRID_X86_ARM64,
        CV_CFL_D3D11_SHADER = 256
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
    }
}
